### ISSUE TITLE
fpindex.pkl

### ISSUE THREAD

**Issue by MachineGUN001** [luost26/ChemProjector#11]

**Comment by MachineGUN001** [comment]
hi, @luost26 thanks for your help. I've put the catalog .sdf and processed.zip into the data folder, and try to run on unarchive_wizard.py. but the error occured.  could you please help see the error info about that.
[error log.txt](https://github.com/user-attachments/files/17294838/error.log.txt)
how can i unzip the package? thanks,

**Comment by luost26** [comment]
Hi,

The script calls `unzip` command to unarchive the file. It seems that `unzip` is not provided in Windows. Could you try running it on a linux-based environment?

**Comment by MachineGUN001** [comment]
I see. thanks for your help.
