### ISSUE TITLE
Cannot reproduce the results

### ISSUE THREAD

**Issue by shuan4638** [luost26/ChemProjector#15]
I was trying to reproduce the ChEMBL results shown in Table 1 in the paper by using the trained model "original_split.ckpt" with SMILES provided at [test_building_blocks.smi](https://github.com/luost26/ChemProjector/blob/main/data/synthesis_planning/test_building_blocks.smi).

For preprocessing, I change the line
`_default_sdf_path = pathlib.Path("data/Enamine_Rush-Delivery_Building_Blocks-US_223244cmpd_20231001.sdf")`
in [create_fingerprint_index.py](https://github.com/luost26/ChemProjector/blob/main/scripts/preprocess_data/create_fingerprint_index.py) and [create_reaction_matrix.py](https://github.com/luost26/ChemProjector/blob/main/scripts/preprocess_data/create_reaction_matrix.py)
to 
`_default_sdf_path = pathlib.Path("data/synthesis_planning/test_building_blocks.smi")`

I got the following results after the command
`python sample.py --model-path data/original_split.ckpt --input data/test_files/test_chembl.csv --output results/chembl.csv`

![image](https://github.com/user-attachments/assets/9e0362cb-0e3e-4fee-9e91-daba04837853)

This results in quite different from the one shown in the paper. Do you know which step of my implementation may be wrong?

Thanks,

**Comment by luost26** [comment]
The RDKit in your environment might be broken so that it cannot give correct fingerprints. I encountered this issue during development. Please try creating a new environment and install the packages following the instruction.

Also, this is not a reproducibility issue.

**Comment by shuan4638** [comment]
I did follow the instructions to create the chemprojector virtual environment and all the packages. 
The installed rdkit version is 2024.09.2.

To check whether the installed rdkit caused issues, I did the following test:
```
from rdkit import Chem
from rdkit.Chem import AllChem

smiles = 'Cc1csc(NC(=O)c2cccnc2N2CCOCC2)n1' # the first SMILES in ChEMBL test set
mol = Chem.MolFromSmiles(smiles)
bit_vec = AllChem.GetMorganFingerprintAsBitVect(mol, 2, 256)
fp_idx = [i for i, bit in enumerate(bit_vec) if bit]
print (fp_idx)
```

and I got 
`[11, 19, 24, 31, 33, 39, 40, 63, 64, 74, 79, 81, 100, 112, 117, 120, 122, 125, 128, 129, 130, 132, 138, 144, 151, 158, 159, 161, 163, 167, 170, 172, 182, 186, 190, 192, 195, 199, 200, 214, 230, 246]`

I also double-checked using the rdkit installed in my other existing environments (2023.03.2 and 2023.09.2), and they all gave the same results. Can you show me what the correct fingerprint should look like?

Thank you.

**Comment by shuan4638** [comment]
I understand, it appears that I misunderstood the method described in the paper. 

Thank you.
