### ISSUE TITLE
Password for preprocessed building block data

### ISSUE THREAD

**Issue by mehradans92** [luost26/ChemProjector#5]
Hi @luost26. Really cool work. I am trying to use your package, but looks like preprocessed building block data that is provided as a zip file has a password. Could I get access? Thanks.

**Comment by luost26** [comment]
Hi Mehrad,

Please run the “unarchive_wizard.py” script. It will verify your ownership
of an Enamine catalog copy and unarchive the zip for you. It will also tell
you what to do if anything is missing.

**Comment by mehradans92** [comment]
Thanks. It worked. Quick question, if I add additional reaction templates to `data/reaction_templates_hb.txt`, do I need to retrain the model or can it use the new reaction templates. The reason I am asking is that let's say we want to explore the chemical space of Aspirin (`CC(=O)OC1=CC=CC=C1C(=O)O`). Not sure why the model output is then `0` steps. It only suggests the SMILES and the synthesis column only repeats the SMILES with no information about the reaction. The bottom rows are also missing all the scores (this was something I noticed happening with other targets as well.). Here is the output:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/15735/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/15735/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


target | smiles | score | synthesis | num_steps | scf_sim | pharm2d_sim | rdkit_sim
-- | -- | -- | -- | -- | -- | -- | --
CC(=O)OC1=CC=CC=C1C(=O)O | CC(=O)Oc1ccccc1C(=O)O | 1 | CC(=O)Oc1ccccc1C(=O)O | 0 | 1 | 1 | 1
CC(=O)OC1=CC=CC=C1C(=O)O | CC(=O)Oc1ccccc1C(C)=O | 0.714 | CC(=O)Oc1ccccc1C(C)=O | 0 | 1 | 0.55 | 0.624
CC(=O)OC1=CC=CC=C1C(=O)O | CC(=O)Oc1cccc(C(=O)O)c1C | 0.71 | CC(=O)Oc1cccc(C(=O)O)c1C | 0 | 1 | 0.31 | 0.532
CC(=O)OC1=CC=CC=C1C(=O)O | CC(=O)Oc1ccccc1C(=O)OC(=O)c1ccccc1OC(C)=O | 0.667 | CC(=O)Oc1ccccc1C(=O)OC(=O)c1ccccc1OC(C)=O | 0 | 0.176 | 0.227 | 0.76
CC(=O)OC1=CC=CC=C1C(=O)O | COc1ccccc1C(=O)O | 0.655 | COc1ccccc1C(=O)O | 0 | 1 | 0.651 | 0.732
CC(=O)OC1=CC=CC=C1C(=O)O | CC(=O)Oc1ccccc1O | 0.6 | CC(=O)Oc1ccccc1O | 0 | 1 | 0.279 | 0.31
CC(=O)OC1=CC=CC=C1C(=O)O | CCOc1ccccc1C(=O)O | 0.594 | CCOc1ccccc1C(=O)O | 0 | 1 | 0.651 | 0.856
CC(=O)OC1=CC=CC=C1C(=O)O | CC(C)Oc1ccccc1C(=O)O | 0.594 | CC(C)Oc1ccccc1C(=O)O | 0 | 1 | 0.651 | 0.806
CC(=O)OC1=CC=CC=C1C(=O)O | Cc1ccccc1Oc1ccccc1C(=O)O | 0.576 | Cc1ccccc1Oc1ccccc1C(=O)O | 0 | 0.25 | 0.412 | 0.453
CC(=O)OC1=CC=CC=C1C(=O)O | O=C(O)c1ccccc1Oc1ccccc1 | 0.562 | O=C(O)c1ccccc1Oc1ccccc1 | 0 | 0.25 | 0.519 | 0.458
CC(=O)OC1=CC=CC=C1C(=O)O | CC(=O)c1ccccc1C(=O)O | 0.552 | CC(=O)c1ccccc1C(=O)O | 0 |   |   |  
CC(=O)OC1=CC=CC=C1C(=O)O | O=C(O)c1ccccc1C(=O)O | 0.538 | O=C(O)c1ccccc1C(=O)O | 0 |   |   |  
CC(=O)OC1=CC=CC=C1C(=O)O | COc1ccccc1-c1ccccc1C(=O)O | 0.529 | COc1ccccc1-c1ccccc1C(=O)O | 0 |   |   |  
CC(=O)OC1=CC=CC=C1C(=O)O | CCOc1ccccc1Oc1ccccc1C(=O)O | 0.528 | CCOc1ccccc1Oc1ccccc1C(=O)O | 0 |   |   |  
CC(=O)OC1=CC=CC=C1C(=O)O | O=C(O)c1ccccc1-c1ccccc1C(=O)O | 0.483 | O=C(O)c1ccccc1-c1ccccc1C(=O)O | 0 |   |   |  


Any thoughts on this behavior?

**Comment by luost26** [comment]
Yes, adding new reaction templates requires preprocessing a new
reaction-reactant matrix and then using it to train a new model. This is
because reactions are represented by one-hot classes so the mode cannot
generalize to unseen reaction templates.

Aspirin and some other similar molecules are already included in the
building block database, so the model immediately finds the matching
building blocks and does not performs synthesis involving multiple building
blocks.

**Comment by luost26** [comment]
About missing scores: evaluating Scaffold similarity, Pharm2D sim., and RDKit sim. is slightly more time-consuming, so they are only evaluted for top-10 analogs ranked by overall Tanimoto similarity. It is possible to calculate these extra similarity scores for more analogs by changing the parameter below:

https://github.com/luost26/ChemProjector/blob/9bb87c2a88d29996de1f8c4c8a97a55a76e94ac5/chemprojector/sampler/state_pool.py#L225
